#pragma once

#define PIN_NUM_MOSFET 5
#define PIN_NUM_PIR 6

#define PIN_NUM_MISO 21 
#define PIN_NUM_MOSI 22
#define PIN_NUM_CLK 23
#define PIN_NUM_CS 7

#define PIN_NUM_CAN_TX 16
#define PIN_NUM_CAN_RX 17

#define PIN_NUM_LED_RED 4
#define PIN_NUM_LED_YELLOW 19
#define PIN_NUM_LED_GREEN 20

#define DEFAULT_CAN_TIMEOUT_MS 100
#define DEFAULT_UDS_TIMEOUT_MS 1000
#define DEFAULT_SLEEP_TIMEOUT_S 60
#define DEFAULT_TERM15_REQUEST_INTERVAL_MS 1000

#define MAX_SPIFFS_FILES 10

typedef enum {
    STATE_DEEPSLEEP,
    STATE_INITILIZING,
    STATE_WAIT_TERM15,
    STATE_IMPORT_CONFIG,
    STATE_LOGGER_IDLE,
    STATE_LOGGING_ACTIVE,
    STATE_UNDEFINED_ERROR,
    STATE_PARSING_CONFIG_ERROR,
    STATE_LOG_ERROR,
    STATE_CAN_ERROR,
    STATE_MEMORY_FULL
} state_id_t;

typedef enum {
    STATE_EVENT_TERM_15_ON,
    STATE_EVENT_TERM_15_OFF,
    STATE_EVENT_TIMEOUT_REACHED,
    STATE_EVENT_WIFI_CONNECTED,
    STATE_EVENT_WIFI_DISCONNECTED,
    STATE_EVENT_WIFI_DATALOGGER_STOP,
    STATE_EVENT_WIFI_DATALOGGER_START,
    STATE_EVENT_CONFIG_LOADED,
    STATE_EVENT_CONFIG_LOADING_FAILED,
    STATE_EVENT_CAN_ERROR,
    STATE_EVENT_MEMORY_FULL,
    STATE_EVENT_LOG_ERROR,
    STATE_EVENT_LOGGING_STARTED,
    STATE_EVENT_LOGGING_STOPPED,
    STATE_EVENT_PIR_TRIGGERED
} state_event_id_t;

typedef enum {
    SYSTEM_EVENT_NEW_CYCLE,
    SYSTEM_EVENT_TIMEOUT_REACHED,
    SYSTEM_EVENT_MEMORY_CHANGED
} system_event_id_t;
